#!/usr/bin/env bash
#
# inject_env_to_swift.sh — read SARVAM_API_KEY + GEMINI_API_KEY +
# GURBANILENS_ASR_URL + GURBANILENS_ASR_TOKEN from the repo-root .env
# file and write them as `static let` constants into the Swift source
# file ios/GurbaniLens/GurbaniLens/Generated/EnvConfig.swift.
#
# The generated file is .gitignored and contains secrets — only ever
# lives on a developer's machine. Compiled into the binary at compile
# time, so providers can read EnvConfig.x without any Bundle / plist
# / runtime lookup.
#
# Replaces inject_env_to_plist.sh (Brief #9.8-iOS, 2026-06-29) which
# mutated the built Info.plist via PlistBuddy. The plist approach
# was intermittently failing across Xcode versions + sandbox modes
# (e.g. ENABLE_USER_SCRIPT_SANDBOXING=YES would silently no-op the
# write). Swift codegen has none of those failure modes — Xcode's
# Compile Sources phase compiles whatever is in the source file,
# end of story.
#
# Wired as a `preBuildScripts` entry in ios/GurbaniLens/project.yml
# so the file is regenerated BEFORE Compile Sources runs every
# build. The script is idempotent: if the rendered content matches
# the existing file byte-for-byte, no write happens (mtime unchanged
# → Xcode's dependency analysis doesn't trigger a needless recompile).
#
# Behaviour:
#   - .env missing            → emit a warning, generate a file with
#                              EMPTY strings (providers throw
#                              "missing key" at start time as before)
#   - key missing in .env     → empty string for that key only
#   - empty value             → empty string
#   - either key set          → real value baked into the constant
#
# Never commits keys back to the repo. .env is gitignored.
# EnvConfig.swift is gitignored.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
TARGET_DIR="$REPO_ROOT/ios/GurbaniLens/GurbaniLens/Generated"
TARGET_FILE="$TARGET_DIR/EnvConfig.swift"

mkdir -p "$TARGET_DIR"

# Defaults — empty strings if anything is missing.
SARVAM_API_KEY=""
GEMINI_API_KEY=""
GURBANILENS_ASR_URL=""
GURBANILENS_ASR_TOKEN=""

if [ ! -f "$ENV_FILE" ]; then
    echo "warning: inject_env_to_swift.sh: $ENV_FILE not found — generating EnvConfig.swift with empty values (cloud providers will surface missing-key errors at start time)"
else
    # Parse .env. Trivial KEY=VALUE; ignore comments + blanks. Strip
    # at most one pair of surrounding quotes. Keys with literal
    # embedded newlines or unescaped = chars are not supported
    # (matches the parsing rules of the old plist script).
    while IFS= read -r line || [ -n "$line" ]; do
        line="${line%$'\r'}"
        case "$line" in
            ''|'#'*) continue ;;
        esac
        key="${line%%=*}"
        value="${line#*=}"
        # Trim leading + trailing whitespace from key.
        key="${key#"${key%%[![:space:]]*}"}"
        key="${key%"${key##*[![:space:]]}"}"
        # Strip surrounding quotes from value (single or double).
        case "$value" in
            \"*\") value="${value#\"}"; value="${value%\"}" ;;
            \'*\') value="${value#\'}"; value="${value%\'}" ;;
        esac
        case "$key" in
            SARVAM_API_KEY)         SARVAM_API_KEY="$value" ;;
            GEMINI_API_KEY)         GEMINI_API_KEY="$value" ;;
            GURBANILENS_ASR_URL)    GURBANILENS_ASR_URL="$value" ;;
            GURBANILENS_ASR_TOKEN)  GURBANILENS_ASR_TOKEN="$value" ;;
        esac
    done < "$ENV_FILE"
fi

# Escape a value for a Swift double-quoted string literal:
# backslash, double-quote, then newlines.
swift_escape() {
    # POSIX-compatible escaping with sed. The chained -e expressions
    # are: escape backslash first (always first!), then quote, then
    # collapse newlines to \n.
    printf '%s' "$1" | sed \
        -e 's/\\/\\\\/g' \
        -e 's/"/\\"/g' \
        -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g'
}

SARVAM_ESC=$(swift_escape "$SARVAM_API_KEY")
GEMINI_ESC=$(swift_escape "$GEMINI_API_KEY")
ASR_URL_ESC=$(swift_escape "$GURBANILENS_ASR_URL")
ASR_TOKEN_ESC=$(swift_escape "$GURBANILENS_ASR_TOKEN")

NEW_CONTENT=$(cat <<EOF
// GENERATED FILE — DO NOT EDIT
// Auto-regenerated by scripts/inject_env_to_swift.sh on every build.
// Source: <repo-root>/.env
// This file is .gitignored — values are local to this developer machine.

import Foundation

public enum EnvConfig {
    public static let sarvamAPIKey: String = "$SARVAM_ESC"
    public static let geminiAPIKey: String = "$GEMINI_ESC"
    public static let gurbanilensASRURL: String = "$ASR_URL_ESC"
    public static let gurbanilensASRToken: String = "$ASR_TOKEN_ESC"
}
EOF
)

# Idempotent write — only touch the file if content actually changed.
# Prevents Xcode dependency analysis from triggering a needless
# recompile when the env values haven't changed between builds.
TMP_FILE=$(mktemp)
printf '%s\n' "$NEW_CONTENT" > "$TMP_FILE"

if [ -f "$TARGET_FILE" ] && cmp -s "$TARGET_FILE" "$TMP_FILE"; then
    rm "$TMP_FILE"
    echo "note: inject_env_to_swift.sh: EnvConfig.swift unchanged — skipping write"
else
    mv "$TMP_FILE" "$TARGET_FILE"
    echo "note: inject_env_to_swift.sh: wrote $TARGET_FILE"
fi

echo "note: inject_env_to_swift.sh: SARVAM_API_KEY len=${#SARVAM_API_KEY} GEMINI_API_KEY len=${#GEMINI_API_KEY} GURBANILENS_ASR_URL len=${#GURBANILENS_ASR_URL} GURBANILENS_ASR_TOKEN len=${#GURBANILENS_ASR_TOKEN}"
