// Bearer-token extraction. The token is an opaque, ephemeral string
// generated by the client; we never persist it server-side beyond the
// rate-limit bucket (which is in-memory and expires after the window).

const BEARER_RE = /^Bearer\s+([A-Za-z0-9._\-=]{8,256})$/;

/**
 * Pull the session token from the Authorization header.
 * Returns the token string or null if missing/malformed.
 */
export function extractBearerToken(req) {
  const h = req.headers.authorization;
  if (typeof h !== "string") return null;
  const m = h.match(BEARER_RE);
  return m ? m[1] : null;
}

/**
 * Fastify preHandler that requires a bearer token. Attaches the token
 * to `req.sessionToken` on success; replies 401 on failure.
 */
export function requireBearer(req, reply, done) {
  const token = extractBearerToken(req);
  if (!token) {
    reply.code(401).send({ error: "missing_or_malformed_bearer_token" });
    return;
  }
  req.sessionToken = token;
  done();
}
